#!/usr/bin/env python3
import subprocess
from pathlib import Path


def main() -> int:

    for test in Path().rglob("*/**/test"):
        print(f"Running {test}")
        subprocess.check_call("./test", cwd=test.parent)

    return 0


if __name__ == "__main__":
    exit(main())
